#pragma once

#include <filesystem>
#include <string>

/** \brief Runtime parameters for the point-cloud-to-skeleton pipeline. */
struct Pipeline_options {
  std::string input_path = "";
  std::string output_dir = "skeleton_output";

  bool enable_spatial_subsampling = false;
  double spatial_subsample_distance = 0.0;
  bool enable_cuda = true;
};

/** \brief File locations generated by the pipeline. */
struct Output_paths {
  std::filesystem::path raw_points;
  std::filesystem::path preprocessed_points;
};
