#include "mesh_reconstruction.h"

#include <CGAL/boost/graph/split_graph_into_polylines.h>
#include <CGAL/compute_average_spacing.h>
#include <CGAL/extract_mean_curvature_flow_skeleton.h>
#include <CGAL/IO/read_points.h>
#include <CGAL/jet_smooth_point_set.h>
#include <CGAL/mst_orient_normals.h>
#include <CGAL/pca_estimate_normals.h>
#include <CGAL/remove_outliers.h>
#include <CGAL/wlop_simplify_and_regularize_point_set.h>

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <limits>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

using Point = mesh_reconstruction::Point;
using Vector = mesh_reconstruction::Vector;
using Pwn = mesh_reconstruction::Pwn;
using Point_map = mesh_reconstruction::Point_map;
using Normal_map = mesh_reconstruction::Normal_map;
using Triangle_mesh = mesh_reconstruction::Triangle_mesh;
using mesh_vertex_descriptor = boost::graph_traits<Triangle_mesh>::vertex_descriptor;

using Skeletonization = CGAL::Mean_curvature_flow_skeletonization<Triangle_mesh>;
using Skeleton = Skeletonization::Skeleton;
using Skeleton_vertex = Skeleton::vertex_descriptor;
using Skeleton_edge = Skeleton::edge_descriptor;

enum class Normal_neighborhood_mode
{
  fixed_k,
  spacing_radius
};

/** \brief Runtime parameters for the point-cloud-to-skeleton pipeline. */
struct Pipeline_options
{
  std::string input_path = "input/RuptDuPuits_Cascades_sampled_5cm_PCV_normals_classified.ply";
  std::string output_dir = "skeleton_output";
  double outlier_percent = 0.0;
  int outlier_neighbors = 24;
  int normal_estimation_neighbors = 24;
  Normal_neighborhood_mode normal_neighborhood_mode = Normal_neighborhood_mode::fixed_k;
  double normal_neighborhood_spacing_multiplier = 2.0;
  bool force_normal_estimation = false;
  bool keep_largest_component = true;
  bool enable_wlop = false;
  bool enable_smoothing = false;
  int smoothing_neighbors = 24;

  // wlop_retain_percent is the percentage of points to retain after WLOP simplification,
  // relative to the input point set size.
  double wlop_retain_percent = 20.0;

  // wlop_neighbor_radius is in the same units as the input point coordinates,
  // and should be set according to the point cloud density.
  // A common choice is to set it to a small multiple (e.g. 2 or 3) of the average spacing of the input points,
  // which can be computed using CGAL::compute_average_spacing.
  double wlop_neighbor_radius = -1.0;
  unsigned int wlop_iterations = 35;
  bool wlop_require_uniform_sampling = false;
};

/** \brief File locations generated by the pipeline. */
struct Output_paths
{
  fs::path raw_points;
  fs::path preprocessed_points;
  fs::path raw_reconstructed_mesh;
  fs::path reconstructed_mesh;
  fs::path skeleton_polylines;
  fs::path skeleton_edges;
  fs::path correspondence;
};

/** \brief Visitor used to serialize skeleton maximal polylines. */
struct Display_polylines
{

  // A polyline is a maximal simple path in the skeleton graph,
  // i.e. a path that cannot be extended at either end without branching.
  const Skeleton &skeleton;
  std::ofstream &out;
  int polyline_size = 0;
  std::stringstream sstr;

  // The visitor is called by CGAL::split_graph_into_polylines for each maximal polyline in the skeleton.
  // It accumulates the points of the current polyline and writes them to the output stream when the polyline ends.
  Display_polylines(const Skeleton &skeleton_ref, std::ofstream &out_ref)
      : skeleton(skeleton_ref), out(out_ref)
  {
  }

  void start_new_polyline()
  {
    polyline_size = 0;
    sstr.str("");
    sstr.clear();
  }

  void add_node(const Skeleton_vertex v)
  {
    ++polyline_size;
    sstr << " " << skeleton[v].point;
  }

  void end_polyline()
  {
    out << polyline_size << sstr.str() << "\n";
  }
};

/** \brief Prints command-line usage for the executable. */
void print_usage(const char *exe_name)
{
  std::cerr << "Usage: " << exe_name
            << " [input_ply] [output_dir] [--remove-outliers-percent=VALUE]"
            << " [--outlier-neighbors=K] [--normal-estimation-neighbors=K]"
            << " [--normal-neighborhood-mode=fixed-k|spacing-radius]"
            << " [--normal-neighborhood-spacing-multiplier=VALUE]"
            << " [--force-estimate-normals] [--keep-all-components]"
            << " [--enable-smoothing] [--smoothing-neighbors=K]"
            << " [--enable-wlop] [--wlop-retain-percent=VALUE]"
            << " [--wlop-neighbor-radius=VALUE] [--wlop-iterations=N]"
            << " [--wlop-require-uniform-sampling]\n";
}

/** \brief Parses command-line options into a pipeline options struct. */
bool parse_args(const int argc, char *argv[], Pipeline_options &options)
{
  if (argc > 1)
  {
    const std::string first = argv[1];
    if (first == "--help" || first == "-h")
    {
      print_usage(argv[0]);
      return false;
    }
    options.input_path = first;
  }

  if (argc > 2)
  {
    options.output_dir = argv[2];
  }

  for (int i = 3; i < argc; ++i)
  {
    const std::string arg = argv[i];

    if (arg.rfind("--remove-outliers-percent=", 0) == 0)
    {
      options.outlier_percent = std::stod(arg.substr(26));
      if (options.outlier_percent < 0.0 || options.outlier_percent >= 100.0)
      {
        std::cerr << "Error: --remove-outliers-percent must be in [0, 100).\n";
        return false;
      }
    }
    else if (arg.rfind("--outlier-neighbors=", 0) == 0)
    {
      options.outlier_neighbors = std::stoi(arg.substr(20));
      if (options.outlier_neighbors < 2)
      {
        std::cerr << "Error: --outlier-neighbors must be >= 2.\n";
        return false;
      }
    }
    else if (arg.rfind("--normal-estimation-neighbors=", 0) == 0)
    {
      options.normal_estimation_neighbors = std::stoi(arg.substr(30));
      if (options.normal_estimation_neighbors < 2)
      {
        std::cerr << "Error: --normal-estimation-neighbors must be >= 2.\n";
        return false;
      }
    }
    else if (arg.rfind("--normal-neighborhood-mode=", 0) == 0)
    {
      const std::string value = arg.substr(std::string("--normal-neighborhood-mode=").size());
      if (value == "fixed-k")
      {
        options.normal_neighborhood_mode = Normal_neighborhood_mode::fixed_k;
      }
      else if (value == "spacing-radius")
      {
        options.normal_neighborhood_mode = Normal_neighborhood_mode::spacing_radius;
      }
      else
      {
        std::cerr << "Error: --normal-neighborhood-mode must be fixed-k or spacing-radius.\n";
        return false;
      }
    }
    else if (arg.rfind("--normal-neighborhood-spacing-multiplier=", 0) == 0)
    {
      options.normal_neighborhood_spacing_multiplier =
          std::stod(arg.substr(std::string("--normal-neighborhood-spacing-multiplier=").size()));
      if (!std::isfinite(options.normal_neighborhood_spacing_multiplier) ||
          options.normal_neighborhood_spacing_multiplier <= 0.0)
      {
        std::cerr << "Error: --normal-neighborhood-spacing-multiplier must be finite and > 0.\n";
        return false;
      }
    }
    else if (arg == "--force-estimate-normals")
    {
      options.force_normal_estimation = true;
    }
    else if (arg == "--keep-all-components")
    {
      options.keep_largest_component = false;
    }
    else if (arg == "--enable-wlop")
    {
      options.enable_wlop = true;
    }
    else if (arg == "--enable-smoothing")
    {
      options.enable_smoothing = true;
    }
    else if (arg.rfind("--smoothing-neighbors=", 0) == 0)
    {
      options.smoothing_neighbors = std::stoi(arg.substr(std::string("--smoothing-neighbors=").size()));
      options.enable_smoothing = true;
      if (options.smoothing_neighbors < 2)
      {
        std::cerr << "Error: --smoothing-neighbors must be >= 2.\n";
        return false;
      }
    }
    else if (arg.rfind("--wlop-retain-percent=", 0) == 0)
    {
      const std::string prefix = "--wlop-retain-percent=";
      options.wlop_retain_percent = std::stod(arg.substr(prefix.size()));
      options.enable_wlop = true;
      if (options.wlop_retain_percent <= 0.0 || options.wlop_retain_percent > 100.0)
      {
        std::cerr << "Error: --wlop-retain-percent must be in (0, 100].\n";
        return false;
      }
    }
    else if (arg.rfind("--wlop-neighbor-radius=", 0) == 0)
    {
      const std::string prefix = "--wlop-neighbor-radius=";
      options.wlop_neighbor_radius = std::stod(arg.substr(prefix.size()));
      options.enable_wlop = true;
      if (!std::isfinite(options.wlop_neighbor_radius))
      {
        std::cerr << "Error: --wlop-neighbor-radius must be finite.\n";
        return false;
      }
    }
    else if (arg.rfind("--wlop-iterations=", 0) == 0)
    {
      const std::string prefix = "--wlop-iterations=";
      const int iterations = std::stoi(arg.substr(prefix.size()));
      options.enable_wlop = true;
      if (iterations < 1)
      {
        std::cerr << "Error: --wlop-iterations must be >= 1.\n";
        return false;
      }
      options.wlop_iterations = static_cast<unsigned int>(iterations);
    }
    else if (arg == "--wlop-require-uniform-sampling")
    {
      options.wlop_require_uniform_sampling = true;
      options.enable_wlop = true;
    }
    else
    {
      std::cerr << "Error: unknown option: " << arg << "\n";
      print_usage(argv[0]);
      return false;
    }
  }

  return true;
}

/** \brief Emits a stage label to make the pipeline trace easy to follow. */
void log_stage(const std::string &label)
{
  std::cout << "\n[Stage] " << label << "\n";
}

/** \brief Creates the output directory when it does not already exist. */
bool prepare_output_dir(const fs::path &out_dir)
{
  std::error_code ec;
  fs::create_directories(out_dir, ec);
  if (ec)
  {
    std::cerr << "Error: cannot create output directory '" << out_dir.string()
              << "': " << ec.message() << "\n";
    return false;
  }
  return true;
}

/** \brief Builds all output artifact paths from the input stem and output directory. */
Output_paths make_output_paths(const Pipeline_options &options)
{
  const fs::path input(options.input_path);
  const std::string stem = input.stem().string();
  const fs::path out_dir(options.output_dir);

  Output_paths paths;
  paths.raw_points = out_dir / (stem + "_stage1_raw_points.ply");
  paths.preprocessed_points = out_dir / (stem + "_stage1_preprocessed_points.ply");
  paths.raw_reconstructed_mesh = out_dir / (stem + "_stage2_raw_reconstruction_mesh.ply");
  paths.reconstructed_mesh = out_dir / (stem + "_reconstructed_mesh.ply");
  paths.skeleton_polylines = out_dir / (stem + "_skeleton.polylines.txt");
  paths.skeleton_edges = out_dir / (stem + "_skeleton_edges.txt");
  paths.correspondence = out_dir / (stem + "_correspondence.polylines.txt");
  return paths;
}

/** \brief Counts normals that are near zero length.
 *
 * This is a heuristic check to identify points with invalid or missing normals, which can cause issues in Poisson reconstruction.
 *
 * The threshold is set to machine epsilon, which is a very small value.
 *
 * In practice, you might want to use a slightly larger threshold to account for numerical imprecision.
 */
std::size_t count_near_zero_normals(const std::vector<Pwn> &points)
{
  std::size_t zero_normals = 0;
  constexpr double k_min_normal_sq_len = 1e-12;
  for (const Pwn &pwn : points)
  {
    if (!std::isfinite(pwn.second.x()) || !std::isfinite(pwn.second.y()) || !std::isfinite(pwn.second.z()) ||
        pwn.second.squared_length() <= k_min_normal_sq_len)
    {
      ++zero_normals;
    }
  }
  return zero_normals;
}

/** \brief Validates that a point set is usable for reconstruction stages. */
bool validate_point_set(const std::vector<Pwn> &points,
                        const char *context,
                        const bool require_oriented_normals)
{
  if (points.size() < 3)
  {
    std::cerr << "Error: " << context << " needs at least 3 points.\n";
    return false;
  }

  constexpr double k_min_normal_sq_len = 1e-12;
  for (std::size_t index = 0; index < points.size(); ++index)
  {
    const Pwn &pwn = points[index];
    if (!std::isfinite(pwn.first.x()) || !std::isfinite(pwn.first.y()) || !std::isfinite(pwn.first.z()))
    {
      std::cerr << "Error: " << context << " contains a non-finite point at index " << index << ".\n";
      return false;
    }

    if (!std::isfinite(pwn.second.x()) || !std::isfinite(pwn.second.y()) || !std::isfinite(pwn.second.z()))
    {
      std::cerr << "Error: " << context << " contains a non-finite normal at index " << index << ".\n";
      return false;
    }

    if (require_oriented_normals && pwn.second.squared_length() <= k_min_normal_sq_len)
    {
      std::cerr << "Error: " << context << " contains a zero-length normal at index " << index << ".\n";
      return false;
    }
  }

  return true;
}

/** \brief Validates spacing values used by Poisson reconstruction. */
bool validate_average_spacing(const double average_spacing, const char *context)
{
  if (!std::isfinite(average_spacing) || average_spacing <= 0.0)
  {
    std::cerr << "Error: " << context << " must be finite and positive.\n";
    return false;
  }

  return true;
}

/** \brief Estimates and orients normals, removing points that remain unoriented.
 *
 * This function first estimates normals using PCA, then orients them using a minimum spanning tree approach.
 *
 * Points that cannot be oriented (e.g., due to ambiguous local geometry) are removed from the set,
 * as they can cause issues in Poisson reconstruction.
 */
bool estimate_and_orient_normals(std::vector<Pwn> &points,
                                 const int requested_neighbors,
                                 const Normal_neighborhood_mode neighborhood_mode,
                                 const double spacing_multiplier)
{
  if (!validate_point_set(points, "normal estimation input", false))
  {
    return false;
  }

  const std::size_t max_neighbors = points.size() - 1;
  const unsigned int neighbors = static_cast<unsigned int>(
      std::min<std::size_t>(static_cast<std::size_t>(requested_neighbors), max_neighbors));

  if (neighbors < 2)
  {
    std::cerr << "Error: normal estimation requires at least 2 neighbors.\n";
    return false;
  }

  double spacing_for_radius = 0.0;
  if (neighborhood_mode == Normal_neighborhood_mode::spacing_radius)
  {
    spacing_for_radius = CGAL::compute_average_spacing<CGAL::Sequential_tag>(
        points,
        std::min<unsigned int>(neighbors, 12U),
        CGAL::parameters::point_map(Point_map()));

    if (!std::isfinite(spacing_for_radius) || spacing_for_radius <= 0.0)
    {
      std::cerr << "Error: cannot derive a valid spacing for radius-based normal estimation.\n";
      return false;
    }
  }

  if (neighborhood_mode == Normal_neighborhood_mode::spacing_radius)
  {
    const double radius = spacing_multiplier * spacing_for_radius;
    CGAL::pca_estimate_normals<CGAL::Sequential_tag>(
        points,
        neighbors,
        CGAL::parameters::point_map(Point_map())
            .normal_map(Normal_map())
            .neighbor_radius(radius));
    std::cout << "Normal estimation radius: " << radius
              << " (spacing=" << spacing_for_radius
              << ", multiplier=" << spacing_multiplier << ")\n";
  }
  else
  {
    CGAL::pca_estimate_normals<CGAL::Sequential_tag>(
        points,
        neighbors,
        CGAL::parameters::point_map(Point_map()).normal_map(Normal_map()));
  }

  const auto unoriented_begin = CGAL::mst_orient_normals(
      points,
      neighbors,
      CGAL::parameters::point_map(Point_map()).normal_map(Normal_map()));

  const std::size_t unoriented_count = static_cast<std::size_t>(std::distance(unoriented_begin, points.end()));
  if (unoriented_count > 0)
  {
    points.erase(unoriented_begin, points.end());
    std::cout << "Normal orientation: removed " << unoriented_count
              << " point(s) with ambiguous orientation.\n";
  }

  if (points.size() < 3)
  {
    std::cerr << "Error: too few oriented points after normal orientation.\n";
    return false;
  }

  std::cout << "Normal estimation/orientation neighbors: " << neighbors << "\n";
  std::cout << "Points after orientation: " << points.size() << "\n";
  return true;
}

bool smooth_points(std::vector<Pwn> &points, const int requested_neighbors)
{
  if (!validate_point_set(points, "smoothing input", false))
  {
    return false;
  }

  const std::size_t max_neighbors = points.size() - 1;
  const unsigned int neighbors = static_cast<unsigned int>(
      std::min<std::size_t>(static_cast<std::size_t>(requested_neighbors), max_neighbors));

  if (neighbors < 2)
  {
    std::cerr << "Error: smoothing requires at least 2 neighbors.\n";
    return false;
  }

  CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(
      points,
      neighbors,
      CGAL::parameters::point_map(Point_map()));

  std::cout << "Smoothing neighbors: " << neighbors << "\n";
  return validate_point_set(points, "post-smoothing point set", false);
}

/** \brief Loads an oriented point cloud from PLY and validates normals availability.
 *
 * This function attempts to read points and normals from the input PLY file.
 *
 * If normals are missing or unreadable, it falls back to loading just points and marks all normals as zero vectors.
 */
bool load_oriented_points(const std::string &input_path, std::vector<Pwn> &points)
{
  log_stage("1. Load point cloud + normals (PLY)");

  bool loaded_with_normals = CGAL::IO::read_points(
      input_path,
      std::back_inserter(points),
      CGAL::parameters::point_map(Point_map()).normal_map(Normal_map()));

  if (!loaded_with_normals)
  {
    std::vector<Point> raw_points;
    if (!CGAL::IO::read_points(input_path, std::back_inserter(raw_points)))
    {
      std::cerr << "Error: cannot read point set from " << input_path << "\n";
      return false;
    }

    points.clear();
    points.reserve(raw_points.size());
    for (const Point &p : raw_points)
    {
      points.emplace_back(p, Vector(0.0, 0.0, 0.0));
    }

    std::cout << "Input normals were not found/readable. Falling back to zero normals.\n";
  }

  if (!validate_point_set(points, "loaded point set", false))
  {
    return false;
  }

  std::cout << "Loaded points: " << points.size() << "\n";

  return true;
}

/** \brief Optionally downsamples and regularizes points with WLOP, then re-estimates normals.
 *
 * WLOP operates on point positions only, so normals are re-estimated and re-oriented after
 * downsampling before reconstruction.
 */
bool apply_wlop_downsampling(std::vector<Pwn> &points, const Pipeline_options &options)
{
  if (!validate_point_set(points, "WLOP input", false))
  {
    return false;
  }

  const std::size_t input_count = points.size();
  std::vector<Point> downsampled_points;
  downsampled_points.reserve(std::max<std::size_t>(
      3,
      static_cast<std::size_t>(
          std::ceil(static_cast<double>(input_count) * (options.wlop_retain_percent / 100.0)))));

  const double wlop_radius = (options.wlop_neighbor_radius <= 0.0)
                                 ? -1.0
                                 : options.wlop_neighbor_radius;

  CGAL::wlop_simplify_and_regularize_point_set<CGAL::Sequential_tag>(
      points,
      std::back_inserter(downsampled_points),
      CGAL::parameters::point_map(Point_map())
          .select_percentage(options.wlop_retain_percent)
          .neighbor_radius(wlop_radius)
          .number_of_iterations(options.wlop_iterations)
          .require_uniform_sampling(options.wlop_require_uniform_sampling));

  if (downsampled_points.size() < 3)
  {
    std::cerr << "Error: WLOP produced too few points (" << downsampled_points.size()
              << "). Increase --wlop-retain-percent.\n";
    return false;
  }

  points.clear();
  points.reserve(downsampled_points.size());
  for (const Point &p : downsampled_points)
  {
    points.emplace_back(p, Vector(0.0, 0.0, 0.0));
  }

  if (!validate_point_set(points, "WLOP output", false))
  {
    return false;
  }

  std::cout << "WLOP retain percent: " << options.wlop_retain_percent << "\n";
  std::cout << "WLOP neighbor radius: " << options.wlop_neighbor_radius
            << (options.wlop_neighbor_radius <= 0.0 ? " (auto)" : "") << "\n";
  std::cout << "WLOP iterations: " << options.wlop_iterations << "\n";
  std::cout << "WLOP uniform sampling: "
            << (options.wlop_require_uniform_sampling ? "enabled" : "disabled") << "\n";
  std::cout << "WLOP points: " << input_count << " -> " << points.size() << "\n";

  return true;
}

/** \brief Applies optional point-cloud filtering and computes average spacing.
 *
 * This function performs outlier removal, optional WLOP, optional smoothing,
 * normal estimation/orientation, and average spacing computation in that order.
 */
bool preprocess_points(std::vector<Pwn> &points,
                       const Pipeline_options &options,
                       double &average_spacing)
{
  if (!validate_point_set(points, "loaded point set", false))
  {
    return false;
  }

  if (options.outlier_percent > 0.0)
  {
    log_stage("1.2 Outlier removal");
    const auto first_to_remove = CGAL::remove_outliers<CGAL::Sequential_tag>(
        points,
        options.outlier_neighbors,
        CGAL::parameters::point_map(Point_map()).threshold_percent(options.outlier_percent));

    const std::size_t before = points.size();
    points.erase(first_to_remove, points.end());
    std::cout << "Outlier removal: " << (before - points.size()) << " points removed.\n";
  }
  else
  {
    std::cout << "Outlier removal: disabled.\n";
  }

  if (!validate_point_set(points, "post-outlier point set", false))
  {
    return false;
  }

  if (options.enable_wlop)
  {
    log_stage("1.3 WLOP downsampling");
    if (options.wlop_retain_percent < 10.0)
    {
      std::cout << "Warning: WLOP retain percent is very low and may destabilize Poisson reconstruction.\n";
    }
    if (!apply_wlop_downsampling(points, options))
    {
      return false;
    }
  }
  else
  {
    std::cout << "WLOP downsampling: disabled.\n";
  }

  if (!validate_point_set(points, "post-WLOP point set", false))
  {
    return false;
  }

  if (options.enable_smoothing)
  {
    log_stage("1.4 Jet smoothing");
    if (!smooth_points(points, options.smoothing_neighbors))
    {
      return false;
    }
  }
  else
  {
    std::cout << "Smoothing: disabled.\n";
  }

  if (options.force_normal_estimation || count_near_zero_normals(points) > 0)
  {
    log_stage("1.5 Estimate + orient normals");
    if (!estimate_and_orient_normals(points,
                                     options.normal_estimation_neighbors,
                                     options.normal_neighborhood_mode,
                                     options.normal_neighborhood_spacing_multiplier))
    {
      return false;
    }
  }
  else
  {
    std::cout << "Normal estimation: skipped; input normals are already usable.\n";
  }

  if (!validate_point_set(points, "oriented point set", true))
  {
    return false;
  }

  log_stage("1.6 Average spacing");
  average_spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>(
      points,
      6,
      CGAL::parameters::point_map(Point_map()));

  if (!validate_average_spacing(average_spacing, "average spacing"))
  {
    return false;
  }

  std::cout << "Average spacing (k=6): " << average_spacing << "\n";
  return true;
}

/**
 * \brief Writes a point+normal cloud to ASCII PLY.
 *
 * This function writes the points and normals in a PLY format.
 */
bool write_oriented_points_ply(const fs::path &out_path, const std::vector<Pwn> &points)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  out << "ply\n";
  out << "format ascii 1.0\n";
  out << "element vertex " << points.size() << "\n";
  out << "property double x\n";
  out << "property double y\n";
  out << "property double z\n";
  out << "property double nx\n";
  out << "property double ny\n";
  out << "property double nz\n";
  out << "end_header\n";

  out.precision(17);
  for (const Pwn &pwn : points)
  {
    const Point &p = pwn.first;
    const Vector &n = pwn.second;
    out << p.x() << " " << p.y() << " " << p.z() << " "
        << n.x() << " " << n.y() << " " << n.z() << "\n";
  }

  return true;
}

/** \brief Exports a point-cloud snapshot for visualization and logs the stage. */
bool write_point_stage_visualization(const fs::path &out_path,
                                     const std::vector<Pwn> &points,
                                     const std::string &stage_label)
{
  log_stage(stage_label);

  if (!write_oriented_points_ply(out_path, points))
  {
    return false;
  }

  std::cout << "Saved: " << out_path.string() << "\n";
  return true;
}

/** \brief Exports a mesh snapshot for visualization and logs the stage. */
bool write_mesh_stage_visualization(const fs::path &out_path,
                                    const Triangle_mesh &mesh,
                                    const std::string &stage_label)
{
  log_stage(stage_label);

  if (!mesh_reconstruction::write_mesh_ply(out_path, mesh))
  {
    return false;
  }

  std::cout << "Saved: " << out_path.string() << "\n";
  return true;
}

/** \brief Runs mean-curvature-flow skeleton extraction on a closed triangle mesh.
 *
 * The input mesh must be a closed surface mesh.
 *
 * The function does not modify the input mesh, but extracts the skeleton into the output parameter.
 */
bool skeletonize(Triangle_mesh &mesh, Skeleton &skeleton)
{
  log_stage("3. Mean curvature flow skeletonization");

  // The mean curvature flow skeletonization algorithm a method that works
  // by simulating cloth on the surface of the mesh, which gradually contracts it while preserving its topology.
  CGAL::extract_mean_curvature_flow_skeleton(mesh, skeleton);

  std::cout << "Skeleton vertices: " << boost::num_vertices(skeleton) << "\n";
  std::cout << "Skeleton edges: " << boost::num_edges(skeleton) << "\n";

  return boost::num_vertices(skeleton) > 0 && boost::num_edges(skeleton) > 0;
}

/** \brief Writes maximal skeleton polylines as one polyline per row. */
bool write_skeleton_polylines(const fs::path &out_path, const Skeleton &skeleton)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  Display_polylines display(skeleton, out);
  CGAL::split_graph_into_polylines(skeleton, display);
  return true;
}

/** \brief Writes the skeleton as a plain edge list (segment endpoints).
 *
 * The plain edge list is good for applications that only need the skeleton connectivity and geometry,
 * without the maximal polyline structure.
 */
bool write_skeleton_edges(const fs::path &out_path, const Skeleton &skeleton)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  out << "# x1 y1 z1 x2 y2 z2\n";
  for (const Skeleton_edge edge : CGAL::make_range(edges(skeleton)))
  {
    const Skeleton_vertex source_v = source(edge, skeleton);
    const Skeleton_vertex target_v = target(edge, skeleton);
    out << skeleton[source_v].point << " " << skeleton[target_v].point << "\n";
  }
  return true;
}

/** \brief Writes vertex-to-skeleton correspondence as line segments. */
bool write_correspondence(const fs::path &out_path,
                          const Skeleton &skeleton,
                          const Triangle_mesh &mesh)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  // The skeletonization algorithm computes a set of vertices on the input mesh that correspond to each skeleton vertex.
  // This function writes those correspondences as line segments from the skeleton vertex to each corresponding mesh.
  for (const Skeleton_vertex v : CGAL::make_range(vertices(skeleton)))
  {
    for (const mesh_vertex_descriptor vd : skeleton[v].vertices)
    {
      out << "2 " << skeleton[v].point << " " << get(CGAL::vertex_point, mesh, vd) << "\n";
    }
  }
  return true;
}

/** \brief Writes all skeleton artifacts to disk. */
bool write_skeleton_outputs(const Output_paths &paths,
                            const Skeleton &skeleton,
                            const Triangle_mesh &mesh)
{
  log_stage("3.1 Export skeleton artifacts");

  if (!write_skeleton_polylines(paths.skeleton_polylines, skeleton))
  {
    return false;
  }

  if (!write_skeleton_edges(paths.skeleton_edges, skeleton))
  {
    return false;
  }

  if (!write_correspondence(paths.correspondence, skeleton, mesh))
  {
    return false;
  }

  std::cout << "Saved: " << paths.skeleton_polylines.string() << "\n";
  std::cout << "Saved: " << paths.skeleton_edges.string() << "\n";
  std::cout << "Saved: " << paths.correspondence.string() << "\n";
  return true;
}

/** \brief point-cloud to skeleton pipeline. */
int main(int argc, char *argv[])
{
#ifndef CGAL_EIGEN3_ENABLED
  std::cerr << "Error: CGAL_EIGEN3_ENABLED is not defined. "
            << "Install Eigen and configure CGAL with Eigen support.\n";
  return EXIT_FAILURE;
#endif

  Pipeline_options options;
  if (!parse_args(argc, argv, options))
  {
    return EXIT_FAILURE;
  }

  if (!prepare_output_dir(options.output_dir))
  {
    return EXIT_FAILURE;
  }

  const Output_paths output_paths = make_output_paths(options);

  std::vector<Pwn> points;
  if (!load_oriented_points(options.input_path, points))
  {
    return EXIT_FAILURE;
  }

  if (!write_point_stage_visualization(
          output_paths.raw_points,
          points,
          "1.1 Visualize raw input point cloud"))
  {
    return EXIT_FAILURE;
  }

  double average_spacing = 0.0;
  if (!preprocess_points(points, options, average_spacing))
  {
    return EXIT_FAILURE;
  }

  if (!write_point_stage_visualization(
          output_paths.preprocessed_points,
          points,
      "1.7 Visualize preprocessed point cloud"))
  {
    return EXIT_FAILURE;
  }

  Triangle_mesh mesh;
  log_stage("2. Poisson reconstruction");
  if (!mesh_reconstruction::reconstruct_mesh_poisson(points, average_spacing, mesh))
  {
    return EXIT_FAILURE;
  }

  if (!write_mesh_stage_visualization(
          output_paths.raw_reconstructed_mesh,
          mesh,
          "2.1 Visualize raw Poisson reconstruction"))
  {
    return EXIT_FAILURE;
  }

  log_stage("2.2 Mesh normalization and validation");
  if (!mesh_reconstruction::normalize_mesh_for_skeletonization(mesh, options.keep_largest_component))
  {
    return EXIT_FAILURE;
  }

  if (!write_mesh_stage_visualization(
          output_paths.reconstructed_mesh,
          mesh,
          "2.3 Export normalized reconstructed mesh"))
  {
    return EXIT_FAILURE;
  }

  Skeleton skeleton;
  if (!skeletonize(mesh, skeleton))
  {
    std::cerr << "Error: skeleton extraction produced an empty skeleton.\n";
    return EXIT_FAILURE;
  }

  if (!write_skeleton_outputs(output_paths, skeleton, mesh))
  {
    return EXIT_FAILURE;
  }

  std::cout << "\nPipeline completed successfully.\n";
  return EXIT_SUCCESS;
}
