#include "mesh_reconstruction.h"

#include <CGAL/boost/graph/split_graph_into_polylines.h>
#include <CGAL/compute_average_spacing.h>
#include <CGAL/extract_mean_curvature_flow_skeleton.h>
#include <CGAL/IO/read_points.h>
#include <CGAL/remove_outliers.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

using Point = mesh_reconstruction::Point;
using Vector = mesh_reconstruction::Vector;
using Pwn = mesh_reconstruction::Pwn;
using Point_map = mesh_reconstruction::Point_map;
using Normal_map = mesh_reconstruction::Normal_map;
using Triangle_mesh = mesh_reconstruction::Triangle_mesh;
using mesh_vertex_descriptor = boost::graph_traits<Triangle_mesh>::vertex_descriptor;

using Skeletonization = CGAL::Mean_curvature_flow_skeletonization<Triangle_mesh>;
using Skeleton = Skeletonization::Skeleton;
using Skeleton_vertex = Skeleton::vertex_descriptor;
using Skeleton_edge = Skeleton::edge_descriptor;

/** \brief Runtime parameters for the point-cloud-to-skeleton pipeline. */
struct Pipeline_options
{
  std::string input_path = "input/RuptDuPuits_Cascades_sampled_5cm_PCV_normals_classified.ply";
  std::string output_dir = "skeleton_output";
  double outlier_percent = 0.0;
  int outlier_neighbors = 24;
  bool keep_largest_component = true;
};

/** \brief File locations generated by the pipeline. */
struct Output_paths
{
  fs::path raw_points;
  fs::path preprocessed_points;
  fs::path raw_reconstructed_mesh;
  fs::path reconstructed_mesh;
  fs::path skeleton_polylines;
  fs::path skeleton_edges;
  fs::path correspondence;
};

/** \brief Visitor used to serialize skeleton maximal polylines. */
struct Display_polylines
{
  const Skeleton& skeleton;
  std::ofstream& out;
  int polyline_size = 0;
  std::stringstream sstr;

  Display_polylines(const Skeleton& skeleton_ref, std::ofstream& out_ref)
    : skeleton(skeleton_ref), out(out_ref)
  {
  }

  void start_new_polyline()
  {
    polyline_size = 0;
    sstr.str("");
    sstr.clear();
  }

  void add_node(const Skeleton_vertex v)
  {
    ++polyline_size;
    sstr << " " << skeleton[v].point;
  }

  void end_polyline()
  {
    out << polyline_size << sstr.str() << "\n";
  }
};

/** \brief Prints command-line usage for the executable. */
void print_usage(const char* exe_name)
{
  std::cerr << "Usage: " << exe_name
            << " [input_ply] [output_dir] [--remove-outliers-percent=VALUE]"
            << " [--outlier-neighbors=K] [--keep-all-components]\n";
}

/** \brief Parses command-line options into a pipeline options struct. */
bool parse_args(const int argc, char* argv[], Pipeline_options& options)
{
  if (argc > 1)
  {
    const std::string first = argv[1];
    if (first == "--help" || first == "-h")
    {
      print_usage(argv[0]);
      return false;
    }
    options.input_path = first;
  }

  if (argc > 2)
  {
    options.output_dir = argv[2];
  }

  for (int i = 3; i < argc; ++i)
  {
    const std::string arg = argv[i];

    if (arg.rfind("--remove-outliers-percent=", 0) == 0)
    {
      options.outlier_percent = std::stod(arg.substr(26));
      if (options.outlier_percent < 0.0 || options.outlier_percent >= 100.0)
      {
        std::cerr << "Error: --remove-outliers-percent must be in [0, 100).\n";
        return false;
      }
    }
    else if (arg.rfind("--outlier-neighbors=", 0) == 0)
    {
      options.outlier_neighbors = std::stoi(arg.substr(20));
      if (options.outlier_neighbors < 2)
      {
        std::cerr << "Error: --outlier-neighbors must be >= 2.\n";
        return false;
      }
    }
    else if (arg == "--keep-all-components")
    {
      options.keep_largest_component = false;
    }
    else
    {
      std::cerr << "Error: unknown option: " << arg << "\n";
      print_usage(argv[0]);
      return false;
    }
  }

  return true;
}

/** \brief Emits a stage label to make the pipeline trace easy to follow. */
void log_stage(const std::string& label)
{
  std::cout << "\n[Stage] " << label << "\n";
}

/** \brief Creates the output directory when it does not already exist. */
bool prepare_output_dir(const fs::path& out_dir)
{
  std::error_code ec;
  fs::create_directories(out_dir, ec);
  if (ec)
  {
    std::cerr << "Error: cannot create output directory '" << out_dir.string()
              << "': " << ec.message() << "\n";
    return false;
  }
  return true;
}

/** \brief Builds all output artifact paths from the input stem and output directory. */
Output_paths make_output_paths(const Pipeline_options& options)
{
  const fs::path input(options.input_path);
  const std::string stem = input.stem().string();
  const fs::path out_dir(options.output_dir);

  Output_paths paths;
  paths.raw_points = out_dir / (stem + "_stage1_raw_points.ply");
  paths.preprocessed_points = out_dir / (stem + "_stage1_preprocessed_points.ply");
  paths.raw_reconstructed_mesh = out_dir / (stem + "_stage2_raw_reconstruction_mesh.ply");
  paths.reconstructed_mesh = out_dir / (stem + "_reconstructed_mesh.ply");
  paths.skeleton_polylines = out_dir / (stem + "_skeleton.polylines.txt");
  paths.skeleton_edges = out_dir / (stem + "_skeleton_edges.txt");
  paths.correspondence = out_dir / (stem + "_correspondence.polylines.txt");
  return paths;
}

/** \brief Loads an oriented point cloud from PLY and validates normals availability. */
bool load_oriented_points(const std::string& input_path, std::vector<Pwn>& points)
{
  log_stage("1. Load point cloud + normals (PLY)");

  if (!CGAL::IO::read_points(
        input_path,
        std::back_inserter(points),
        CGAL::parameters::point_map(Point_map()).normal_map(Normal_map())))
  {
    std::cerr << "Error: cannot read point set from " << input_path << "\n";
    return false;
  }

  if (points.empty())
  {
    std::cerr << "Error: point set is empty.\n";
    return false;
  }

  std::size_t zero_normals = 0;
  const double eps = std::numeric_limits<double>::epsilon();
  for (const Pwn& pwn : points)
  {
    if (pwn.second.squared_length() <= eps)
    {
      ++zero_normals;
    }
  }

  if (zero_normals == points.size())
  {
    std::cerr << "Error: no valid normals found in input. Poisson reconstruction requires oriented normals.\n";
    return false;
  }

  std::cout << "Loaded points: " << points.size() << "\n";
  if (zero_normals > 0)
  {
    std::cout << "Warning: " << zero_normals
              << " points have near-zero normals. Reconstruction quality may degrade.\n";
  }

  return true;
}

/** \brief Applies optional point-cloud filtering and computes average spacing. */
double preprocess_points(std::vector<Pwn>& points, const Pipeline_options& options)
{
  log_stage("1.2 Optional preprocessing");

  if (options.outlier_percent > 0.0)
  {
    const auto first_to_remove = CGAL::remove_outliers<CGAL::Sequential_tag>(
      points,
      options.outlier_neighbors,
      CGAL::parameters::point_map(Point_map()).threshold_percent(options.outlier_percent));

    const std::size_t before = points.size();
    points.erase(first_to_remove, points.end());
    std::cout << "Outlier removal: " << (before - points.size()) << " points removed.\n";
  }
  else
  {
    std::cout << "Outlier removal: disabled.\n";
  }

  const double average_spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>(
    points,
    6,
    CGAL::parameters::point_map(Point_map()));

  std::cout << "Average spacing (k=6): " << average_spacing << "\n";
  return average_spacing;
}

/**
 * \brief Writes a point+normal cloud to ASCII PLY.
 * \details This creates visualization snapshots for each point-cloud processing stage.
 */
bool write_oriented_points_ply(const fs::path& out_path, const std::vector<Pwn>& points)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  out << "ply\n";
  out << "format ascii 1.0\n";
  out << "element vertex " << points.size() << "\n";
  out << "property double x\n";
  out << "property double y\n";
  out << "property double z\n";
  out << "property double nx\n";
  out << "property double ny\n";
  out << "property double nz\n";
  out << "end_header\n";

  out.precision(17);
  for (const Pwn& pwn : points)
  {
    const Point& p = pwn.first;
    const Vector& n = pwn.second;
    out << p.x() << " " << p.y() << " " << p.z() << " "
        << n.x() << " " << n.y() << " " << n.z() << "\n";
  }

  return true;
}

/** \brief Exports a point-cloud snapshot for visualization and logs the stage. */
bool write_point_stage_visualization(const fs::path& out_path,
                                     const std::vector<Pwn>& points,
                                     const std::string& stage_label)
{
  log_stage(stage_label);

  if (!write_oriented_points_ply(out_path, points))
  {
    return false;
  }

  std::cout << "Saved: " << out_path.string() << "\n";
  return true;
}

/** \brief Exports a mesh snapshot for visualization and logs the stage. */
bool write_mesh_stage_visualization(const fs::path& out_path,
                                    const Triangle_mesh& mesh,
                                    const std::string& stage_label)
{
  log_stage(stage_label);

  if (!mesh_reconstruction::write_mesh_ply(out_path, mesh))
  {
    return false;
  }

  std::cout << "Saved: " << out_path.string() << "\n";
  return true;
}

/** \brief Runs mean-curvature-flow skeleton extraction on a closed triangle mesh. */
bool skeletonize(Triangle_mesh& mesh, Skeleton& skeleton)
{
  log_stage("3. Mean curvature flow skeletonization");

  CGAL::extract_mean_curvature_flow_skeleton(mesh, skeleton);

  std::cout << "Skeleton vertices: " << boost::num_vertices(skeleton) << "\n";
  std::cout << "Skeleton edges: " << boost::num_edges(skeleton) << "\n";

  return boost::num_vertices(skeleton) > 0 && boost::num_edges(skeleton) > 0;
}

/** \brief Writes maximal skeleton polylines as one polyline per row. */
bool write_skeleton_polylines(const fs::path& out_path, const Skeleton& skeleton)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  Display_polylines display(skeleton, out);
  CGAL::split_graph_into_polylines(skeleton, display);
  return true;
}

/** \brief Writes the skeleton as a plain edge list (segment endpoints). */
bool write_skeleton_edges(const fs::path& out_path, const Skeleton& skeleton)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  out << "# x1 y1 z1 x2 y2 z2\n";
  for (const Skeleton_edge edge : CGAL::make_range(edges(skeleton)))
  {
    const Skeleton_vertex source_v = source(edge, skeleton);
    const Skeleton_vertex target_v = target(edge, skeleton);
    out << skeleton[source_v].point << " " << skeleton[target_v].point << "\n";
  }
  return true;
}

/** \brief Writes vertex-to-skeleton correspondence as line segments. */
bool write_correspondence(const fs::path& out_path,
                          const Skeleton& skeleton,
                          const Triangle_mesh& mesh)
{
  std::ofstream out(out_path.string());
  if (!out)
  {
    std::cerr << "Error: cannot open " << out_path.string() << " for writing.\n";
    return false;
  }

  for (const Skeleton_vertex v : CGAL::make_range(vertices(skeleton)))
  {
    for (const mesh_vertex_descriptor vd : skeleton[v].vertices)
    {
      out << "2 " << skeleton[v].point << " " << get(CGAL::vertex_point, mesh, vd) << "\n";
    }
  }
  return true;
}

/** \brief Writes all skeleton artifacts to disk. */
bool write_skeleton_outputs(const Output_paths& paths,
                            const Skeleton& skeleton,
                            const Triangle_mesh& mesh)
{
  log_stage("3.1 Export skeleton artifacts");

  if (!write_skeleton_polylines(paths.skeleton_polylines, skeleton))
  {
    return false;
  }

  if (!write_skeleton_edges(paths.skeleton_edges, skeleton))
  {
    return false;
  }

  if (!write_correspondence(paths.correspondence, skeleton, mesh))
  {
    return false;
  }

  std::cout << "Saved: " << paths.skeleton_polylines.string() << "\n";
  std::cout << "Saved: " << paths.skeleton_edges.string() << "\n";
  std::cout << "Saved: " << paths.correspondence.string() << "\n";
  return true;
}

/** \brief point-cloud to skeleton pipeline. */
int main(int argc, char* argv[])
{
#ifndef CGAL_EIGEN3_ENABLED
  std::cerr << "Error: CGAL_EIGEN3_ENABLED is not defined. "
            << "Install Eigen and configure CGAL with Eigen support.\n";
  return EXIT_FAILURE;
#endif

  Pipeline_options options;
  if (!parse_args(argc, argv, options))
  {
    return EXIT_FAILURE;
  }

  if (!prepare_output_dir(options.output_dir))
  {
    return EXIT_FAILURE;
  }

  const Output_paths output_paths = make_output_paths(options);

  std::vector<Pwn> points;
  if (!load_oriented_points(options.input_path, points))
  {
    return EXIT_FAILURE;
  }

  if (!write_point_stage_visualization(
        output_paths.raw_points,
        points,
        "1.1 Visualize raw input point cloud"))
  {
    return EXIT_FAILURE;
  }

  const double average_spacing = preprocess_points(points, options);

  if (!write_point_stage_visualization(
        output_paths.preprocessed_points,
        points,
        "1.3 Visualize preprocessed point cloud"))
  {
    return EXIT_FAILURE;
  }

  Triangle_mesh mesh;
  log_stage("2. Poisson reconstruction");
  if (!mesh_reconstruction::reconstruct_mesh_poisson(points, average_spacing, mesh))
  {
    return EXIT_FAILURE;
  }

  if (!write_mesh_stage_visualization(
        output_paths.raw_reconstructed_mesh,
        mesh,
        "2.1 Visualize raw Poisson reconstruction"))
  {
    return EXIT_FAILURE;
  }

  log_stage("2.2 Mesh normalization and validation");
  if (!mesh_reconstruction::normalize_mesh_for_skeletonization(mesh, options.keep_largest_component))
  {
    return EXIT_FAILURE;
  }

  if (!write_mesh_stage_visualization(
        output_paths.reconstructed_mesh,
        mesh,
        "2.3 Export normalized reconstructed mesh"))
  {
    return EXIT_FAILURE;
  }

  Skeleton skeleton;
  if (!skeletonize(mesh, skeleton))
  {
    std::cerr << "Error: skeleton extraction produced an empty skeleton.\n";
    return EXIT_FAILURE;
  }

  if (!write_skeleton_outputs(output_paths, skeleton, mesh))
  {
    return EXIT_FAILURE;
  }

  std::cout << "\nPipeline completed successfully.\n";
  return EXIT_SUCCESS;
}
